import { NextRequest, NextResponse } from 'next/server'
import { getAuthedUser, unauthorized } from '../../lib/auth'

export async function POST(req: NextRequest) {
  const user = await getAuthedUser()
  if (!user) return unauthorized()

  const { type, content, userName } = await req.json()
  if (!content) {
    return NextResponse.json({ error: 'Missing content' }, { status: 400 })
  }

  const title = type === 'taper' ? 'Tapering Plan'
    : type === 'meal' ? 'Meal Plan'
    : type === 'exercise' ? 'Exercise Plan'
    : 'Plan'

  const date = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

  // Convert plain text content to HTML paragraphs, preserving line breaks
  const contentHtml = content
    .split('\n')
    .map((line: string) => {
      const trimmed = line.trim()
      if (!trimmed) return '<div style="height:12px"></div>'
      // Detect section headers (ALL CAPS lines or lines ending with colon)
      if (trimmed === trimmed.toUpperCase() && trimmed.length > 3 && !trimmed.startsWith('-') && !trimmed.startsWith('→')) {
        return `<h2 style="font-size:15px;font-weight:700;color:#2D5A3D;margin:18px 0 6px 0;letter-spacing:0.5px">${trimmed}</h2>`
      }
      if (trimmed.startsWith('Phase ') || trimmed.startsWith('PHASE ')) {
        return `<h3 style="font-size:14px;font-weight:700;color:#1E1E1C;margin:16px 0 4px 0;border-bottom:1px solid #E8E8E4;padding-bottom:4px">${trimmed}</h3>`
      }
      if (trimmed.startsWith('- ')) {
        return `<div style="padding-left:16px;margin:3px 0;color:#444">${trimmed}</div>`
      }
      if (trimmed.startsWith('→')) {
        return `<div style="padding-left:16px;margin:3px 0;color:#2D5A3D;font-weight:600">${trimmed}</div>`
      }
      return `<p style="margin:4px 0;color:#333;line-height:1.6">${trimmed}</p>`
    })
    .join('\n')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${userName ? `${userName}'s ` : ''}${title} — NovuraHealth</title>
<style>
  @media print {
    body { margin: 0; }
    .no-print { display: none; }
  }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 700px;
    margin: 0 auto;
    padding: 0;
    color: #1E1E1C;
    font-size: 13px;
    line-height: 1.5;
  }
  .header {
    background: #2D5A3D;
    padding: 24px 32px;
    color: white;
  }
  .header h1 {
    font-size: 20px;
    font-weight: 700;
    margin: 0 0 4px 0;
  }
  .header p {
    font-size: 12px;
    opacity: 0.7;
    margin: 0;
  }
  .content {
    padding: 24px 32px;
  }
  .meta {
    font-size: 11px;
    color: #8B8B83;
    margin-bottom: 20px;
    padding-bottom: 12px;
    border-bottom: 1px solid #EDEDEA;
  }
  .footer {
    margin-top: 40px;
    padding: 16px 32px;
    background: #F5F5F2;
    font-size: 10px;
    color: #8B8B83;
    line-height: 1.6;
  }
  .print-btn {
    position: fixed;
    top: 16px;
    right: 16px;
    background: #2D5A3D;
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 8px;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
  }
  .print-btn:hover { background: #3A7A52; }
</style>
</head>
<body>
<button class="print-btn no-print" onclick="window.print()">Save as PDF</button>

<div class="header">
  <h1>${userName ? `${userName}'s ` : ''}${title}</h1>
  <p>NovuraHealth AI Coach</p>
</div>

<div class="content">
  <div class="meta">Generated ${date}</div>
  ${contentHtml}
</div>

<div class="footer">
  <p>Generated by NovuraHealth AI Coach — novurahealth.com</p>
  <p style="margin-top:8px">This plan is for informational purposes only. Consult your healthcare provider before making changes to your medication or health regimen.</p>
</div>
</body>
</html>`

  return new NextResponse(html, {
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  })
}
